CREATE TABLE MeasureDefinition (idMeasureDef NUMBER(10) NOT NULL, measureName VARCHAR, measureType VARCHAR, PRIMARY KEY (idMeasureDef))
CREATE TABLE MeasureDefaultRange (idRange NUMBER(10) NOT NULL, alarmLevel VARCHAR, endValue VARCHAR, rangeName VARCHAR, startValue VARCHAR, idMeasureDef NUMBER(10), PRIMARY KEY (idRange))
CREATE TABLE Person (idPerson NUMBER(19) NOT NULL, birthdate VARCHAR, email VARCHAR, lastname VARCHAR, name VARCHAR, username VARCHAR, PRIMARY KEY (idPerson))
CREATE TABLE Goal (idGoal NUMBER(10) NOT NULL, deadline NUMBER(19), value VARCHAR, idMeasureDef NUMBER(10), idPerson NUMBER(19), PRIMARY KEY (idGoal))
CREATE TABLE HealthMeasureHistory (idMeasureHistory NUMBER(10) NOT NULL, timestamp VARCHAR, value VARCHAR, idMeasureDef NUMBER(10), idPerson NUMBER(19), PRIMARY KEY (idMeasureHistory))
CREATE TABLE LifeStatus (idMeasure NUMBER(10) NOT NULL, value VARCHAR, idMeasureDef NUMBER(10), idPerson NUMBER(19), PRIMARY KEY (idMeasure))
ALTER TABLE MeasureDefaultRange ADD CONSTRAINT FK_MeasureDefaultRange_idMeasureDef FOREIGN KEY (idMeasureDef) REFERENCES MeasureDefinition (idMeasureDef)
ALTER TABLE Goal ADD CONSTRAINT FK_Goal_idMeasureDef FOREIGN KEY (idMeasureDef) REFERENCES MeasureDefinition (idMeasureDef)
ALTER TABLE Goal ADD CONSTRAINT FK_Goal_idPerson FOREIGN KEY (idPerson) REFERENCES Person (idPerson)
ALTER TABLE HealthMeasureHistory ADD CONSTRAINT FK_HealthMeasureHistory_idMeasureDef FOREIGN KEY (idMeasureDef) REFERENCES MeasureDefinition (idMeasureDef)
ALTER TABLE HealthMeasureHistory ADD CONSTRAINT FK_HealthMeasureHistory_idPerson FOREIGN KEY (idPerson) REFERENCES Person (idPerson)
ALTER TABLE LifeStatus ADD CONSTRAINT FK_LifeStatus_idPerson FOREIGN KEY (idPerson) REFERENCES Person (idPerson)
ALTER TABLE LifeStatus ADD CONSTRAINT FK_LifeStatus_idMeasureDef FOREIGN KEY (idMeasureDef) REFERENCES MeasureDefinition (idMeasureDef)
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMBER(19), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
