
package introsde.wrapper.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WrapperUpdaterService", targetNamespace = "http://ws.wrapper.introsde/", wsdlLocation = "http://localhost:6904/ws/lifecoach/wrapperupdater?wsdl")
public class WrapperUpdaterService_Service
    extends Service
{

    private final static URL WRAPPERUPDATERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WRAPPERUPDATERSERVICE_EXCEPTION;
    private final static QName WRAPPERUPDATERSERVICE_QNAME = new QName("http://ws.wrapper.introsde/", "WrapperUpdaterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6904/ws/lifecoach/wrapperupdater?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WRAPPERUPDATERSERVICE_WSDL_LOCATION = url;
        WRAPPERUPDATERSERVICE_EXCEPTION = e;
    }

    public WrapperUpdaterService_Service() {
        super(__getWsdlLocation(), WRAPPERUPDATERSERVICE_QNAME);
    }

    public WrapperUpdaterService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WRAPPERUPDATERSERVICE_QNAME, features);
    }

    public WrapperUpdaterService_Service(URL wsdlLocation) {
        super(wsdlLocation, WRAPPERUPDATERSERVICE_QNAME);
    }

    public WrapperUpdaterService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WRAPPERUPDATERSERVICE_QNAME, features);
    }

    public WrapperUpdaterService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WrapperUpdaterService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WrapperUpdaterService
     */
    @WebEndpoint(name = "WrapperUpdaterServiceImplPort")
    public WrapperUpdaterService getWrapperUpdaterServiceImplPort() {
        return super.getPort(new QName("http://ws.wrapper.introsde/", "WrapperUpdaterServiceImplPort"), WrapperUpdaterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WrapperUpdaterService
     */
    @WebEndpoint(name = "WrapperUpdaterServiceImplPort")
    public WrapperUpdaterService getWrapperUpdaterServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wrapper.introsde/", "WrapperUpdaterServiceImplPort"), WrapperUpdaterService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WRAPPERUPDATERSERVICE_EXCEPTION!= null) {
            throw WRAPPERUPDATERSERVICE_EXCEPTION;
        }
        return WRAPPERUPDATERSERVICE_WSDL_LOCATION;
    }

}
