
package introsde.wrapper.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WrapperUpdaterService", targetNamespace = "http://ws.wrapper.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WrapperUpdaterService {


    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "userId", targetNamespace = "")
    @RequestWrapper(localName = "getUserId", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetUserIdResponse")
    @Action(input = "http://ws.wrapper.introsde/WrapperUpdaterService/getUserIdRequest", output = "http://ws.wrapper.introsde/WrapperUpdaterService/getUserIdResponse")
    public Long getUserId(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.util.List<introsde.wrapper.ws.MeasureActivity>
     */
    @WebMethod
    @WebResult(name = "fitnessActivities", targetNamespace = "")
    @RequestWrapper(localName = "getFitnessActivities", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetFitnessActivities")
    @ResponseWrapper(localName = "getFitnessActivitiesResponse", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetFitnessActivitiesResponse")
    @Action(input = "http://ws.wrapper.introsde/WrapperUpdaterService/getFitnessActivitiesRequest", output = "http://ws.wrapper.introsde/WrapperUpdaterService/getFitnessActivitiesResponse")
    public List<MeasureActivity> getFitnessActivities(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.util.List<introsde.wrapper.ws.MeasureWeight>
     */
    @WebMethod
    @WebResult(name = "weight", targetNamespace = "")
    @RequestWrapper(localName = "getMeasureHistoryFromWeightRK", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetMeasureHistoryFromWeightRK")
    @ResponseWrapper(localName = "getMeasureHistoryFromWeightRKResponse", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetMeasureHistoryFromWeightRKResponse")
    @Action(input = "http://ws.wrapper.introsde/WrapperUpdaterService/getMeasureHistoryFromWeightRKRequest", output = "http://ws.wrapper.introsde/WrapperUpdaterService/getMeasureHistoryFromWeightRKResponse")
    public List<MeasureWeight> getMeasureHistoryFromWeightRK(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "PersonJson", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetUserResponse")
    @Action(input = "http://ws.wrapper.introsde/WrapperUpdaterService/getUserRequest", output = "http://ws.wrapper.introsde/WrapperUpdaterService/getUserResponse")
    public String getUser(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

}
