
package introsde.wrapper.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import introsde.storage.ws.HealthMeasureHistory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WrapperUpdaterService", targetNamespace = "http://ws.wrapper.introsde/")
@XmlSeeAlso({
    introsde.storage.ws.ObjectFactory.class,
    introsde.wrapper.ws.ObjectFactory.class
})
public interface WrapperUpdaterService {


    /**
     * 
     * @param accessToken
     * @return
     *     returns introsde.wrapper.ws.Activities
     */
    @WebMethod
    @WebResult(name = "fitnessActivities", targetNamespace = "")
    @RequestWrapper(localName = "getFitnessActivities", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetFitnessActivities")
    @ResponseWrapper(localName = "getFitnessActivitiesResponse", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetFitnessActivitiesResponse")
    @Action(input = "http://ws.wrapper.introsde/WrapperUpdaterService/getFitnessActivitiesRequest", output = "http://ws.wrapper.introsde/WrapperUpdaterService/getFitnessActivitiesResponse")
    public Activities getFitnessActivities(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.util.List<introsde.storage.ws.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "weight", targetNamespace = "")
    @RequestWrapper(localName = "getMeasureHistoryFromWeightRK", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetMeasureHistoryFromWeightRK")
    @ResponseWrapper(localName = "getMeasureHistoryFromWeightRKResponse", targetNamespace = "http://ws.wrapper.introsde/", className = "introsde.wrapper.ws.GetMeasureHistoryFromWeightRKResponse")
    @Action(input = "http://ws.wrapper.introsde/WrapperUpdaterService/getMeasureHistoryFromWeightRKRequest", output = "http://ws.wrapper.introsde/WrapperUpdaterService/getMeasureHistoryFromWeightRKResponse")
    public List<HealthMeasureHistory> getMeasureHistoryFromWeightRK(
        @WebParam(name = "accessToken", targetNamespace = "")
        String accessToken);

}
